name: Node CI/CD example

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    builds:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
          
            - name: Node Setup
              uses: actions/setup-node@v4
              with:
                node-version: 22
            
            - name: Install Dependencies
              run: npm install --legacy-peer-deps
            
            - name: Creating Environment Variables
              run: touch .env

            - name: Inserting Variable in .env
              run: echo "HELLO=${{ secrets.HELLO }}" >> .env

             
            - name: Creating Build
              run: npm run build
             
            - name: Starting Service
              run: npm run start &

            - name: Service Started
              run: echo "Service Started Successfully"


