name: Node CI/CD example

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    builds:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
          
            - name: Node Setup
              uses: actions/setup-node@v4
              with:
                node-version: 22
            
            - name: Install Dependencies
              uses: npm install --legacy-peer-deps

            - name: Creating Build
              uses: npm run build
            
            - name: Starting Service
              uses: npm run start

            - name: Service Started
              uses: echo "Service Started Successfully"


